export const SERVICES = [
  {
    name: "Fade",
    description: "Moderno fade šišanje sa preciznim prelazima",
    price: 8,
    durationMinutes: 40,
    sortOrder: 1,
  },
  {
    name: "Klasično šišanje",
    description: "Tradicionalno šišanje makazama i mašinicom",
    price: 6,
    durationMinutes: 20,
    sortOrder: 2,
  },
  {
    name: "Fade + brada",
    description: "Fade šišanje i uređivanje brade",
    price: 11,
    durationMinutes: 40,
    sortOrder: 3,
  },
  {
    name: "Klasično + brada",
    description: "Klasično šišanje i uređivanje brade",
    price: 9,
    durationMinutes: 30,
    sortOrder: 4,
  },
  {
    name: "Fade + pranje",
    description: "Fade šišanje sa pranjem kose",
    price: 10,
    durationMinutes: 40,
    sortOrder: 5,
  },
  {
    name: "Klasično + pranje",
    description: "Klasično šišanje sa pranjem kose",
    price: 8,
    durationMinutes: 30,
    sortOrder: 6,
  },
  {
    name: "Fade + brada + pranje",
    description: "Fade, brada i pranje kose",
    price: 13,
    durationMinutes: 50,
    sortOrder: 7,
  },
  {
    name: "Klasično + brada + pranje",
    description: "Klasično šišanje, brada i pranje kose",
    price: 11,
    durationMinutes: 40,
    sortOrder: 8,
  },
  {
    name: "Fade + masaža",
    description: "Fade šišanje i relaksirajuća masaža glave",
    price: 13,
    durationMinutes: 50,
    sortOrder: 9,
  },
  {
    name: "Klasično + masaža",
    description: "Klasično šišanje i masaža glave",
    price: 11,
    durationMinutes: 40,
    sortOrder: 10,
  },
  {
    name: "Fade komplet",
    description: "Fade, brada i masaža glave — puna usluga",
    price: 15,
    durationMinutes: 60,
    sortOrder: 11,
  },
  {
    name: "Klasično komplet",
    description: "Klasično šišanje, brada i masaža glave",
    price: 13,
    durationMinutes: 50,
    sortOrder: 12,
  },
] as const;
